### ISSUE TITLE
No grid items found

### ISSUE THREAD

**Issue by lawik** [monostream/tifig#12]
I've just compiled this and I'm trying the samples found at https://nokiatech.github.io/heif/examples.html and getting only the message "No grid items founds!" on all the ones I've tried. Any clue if I've messed something up?

**Comment by monostefan** [comment]
This is expected behaviour at the moment ;). As we state in the Readme: "Converts HEIF images created on iOS 11 devices", tifig is currently focused excclusively on those photos shot with an iPhone 7 or newer devices. Those HEIF images are based on HEVC encoded tiles layed out in a grid. To support the whole HEIF standard, quite some more work would be needed: Support for other encodings (AVC, JPG, TIFF), image collections, time based animations, derived images, media content and you name it.

However, what we will do is improve that error message.

**Comment by lawik** [comment]
Seems to work on the iOS ones I have, yes. This format seems a bit complex when two different still images are that different.

Good job at any rate, this will help us quite a bit.

**Comment by monostefan** [comment]
Jup, the whole HEIF standard is pretty large and complex ;). However, we might implement single frame HEVC encoded HEIFs at some future point, shouldn't be too complex with what we already have.

The error message [has been improved](https://github.com/monostream/tifig/commit/450904110944df4224b225591f13182306bfe975) in the meanwhile, so I'm closing this ticket.
