### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by Daij-Djan** [monostream/tifig#2]
make fails

```
-- Checking for one of the modules 'vips-cpp'
CMake Error at /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindPkgConfig.cmake:640 (message):
  None of the required 'vips-cpp' found
Call Stack (most recent call first):
  CMakeLists.txt:6 (pkg_search_module)
```

**Comment by monostefan** [comment]
Hi @Daij-Djan, thanks for your interest in tifig! It seems like you haven't installed libvips dev headers. If you are running a debian based system, try this:

    # sudo apt-get install libvips-dev libavcodec-dev libswscale-dev

On OSX, this should get you going:

    # brew install libvips libav

Please let me know if this works for you.

**Comment by Daij-Djan** [comment]
I didnt know that. thx.  works fine

**Comment by peacedyc33** [comment]
Hi @monostefan, what if I use centos?
I have installed vips built by git and it seems success since I can see following files in /usr/local/lib/

> ./usr/local/lib/libvips-cpp.a
./usr/local/lib/libvipsCC.so
./usr/local/lib/libvips-cpp.so.42.8.1
./usr/local/lib/libvips-cpp.so
./usr/local/lib/libvips.so.42
./usr/local/lib/libvips.a
./usr/local/lib/libvipsCC.so.42
./usr/local/lib/libvips.la
./usr/local/lib/libvips.so.42.8.1
./usr/local/lib/libvips-cpp.so.42
./usr/local/lib/libvipsCC.la
./usr/local/lib/libvips.so
./usr/local/lib/libvips-cpp.la
./usr/local/lib/libvipsCC.a
./usr/local/lib/libvipsCC.so.42.8.1

But it still says

> -- Checking for module 'vips-cpp'
--   No package 'vips-cpp' found
CMake Error at /usr/share/cmake3/Modules/FindPkgConfig.cmake:424 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake3/Modules/FindPkgConfig.cmake:597 (_pkg_check_modules_internal)
  CMakeLists.txt:29 (pkg_check_modules)


> 
when I try to run cmake3 ..

Can you advise what the issue is?

**Comment by Flask** [comment]
@peacedyc33 have you ran ldconfig after compiling vips?

could you paste the the output of ‘pkg-config vips-cpp --libs‘?

**Comment by peacedyc33** [comment]
@Flask 

> -L/usr/local/lib -lvips-cpp -lvips -lgobject-2.0 -lglib-2.0  

I have run ldconfig, it was not set up. I just set it manually. Above is the output of ‘pkg-config vips-cpp --libs‘. And the message for building tifig is still the same.

**Comment by peacedyc33** [comment]
Hi @Flask,
Yesterday issue has solved by build from a source tarball instead of github.
I can build tifig now, but when I run it, there is an error below:

> tifig: error while loading shared libraries: libavcodec.so.57: cannot open shared object file: No such file or directory
